version: '2.3'
services:
  ros:
    build: ./ros
    image: axyz1288/aidocker:ros
    container_name: ros
    runtime: nvidia
    user: aiRobots
    volumes:
      - ~/aiRobots/ros:/home/aiRobots
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /dev:/dev
    environment: 
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"

  cpp:
    build: ./cpp
    depends_on: [ros]
    image: axyz1288/aidocker:cpp
    container_name: cpp
    runtime: nvidia
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots/cpp:/home/aiRobots
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
    environment:
      - "ROS_HOSTNAME=cpp"
      - "ROS_MASTER_URI=http://ros:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"
  base:
    build: ./python
    image: axyz1288/aidocker:python
    container_name: python

  pytorch:
    build: ./pytorch
    depends_on: [base]
    image: axyz1288/aidocker:pytorch
    container_name: pytorch
    runtime: nvidia
    user: aiRobots
    shm_size: '128gb'
    ports:
      - "1010:8888"
      - "1011:6006"
    volumes:
      - ~/aiRobots/pytorch:/home/aiRobots
    environment:
      - "ROS_HOSTNAME=pytorch"
      - "ROS_MASTER_URI=http://ros:11311"

  # Not support cuda 11.0
  # tensorflow:
  #   build: ./tensorflow
  #   depends_on: [base]
  #   image: axyz1288/aidocker:tensorflow
  #   container_name: tensorflow
  #   runtime: nvidia
  #   user: aiRobots
  #   shm_size: '128gb'
  #   ports:
  #     - "1020:8888"
  #     - "1021:6006"
  #   volumes:
  #     - ~/aiRobots/tensorflow:/home/aiRobots
  #   environment:
  #     - "ROS_HOSTNAME=tensorflow"
  #     - "ROS_MASTER_URI=http://ros:11311"