version: '2.3'
services:
  ros:
    build: ./ros
    image: axyz1288/ros:kinetic
    runtime: nvidia
    user: aiRobots
    container_name: ros
    volumes:
      - ~/aiRobots/ros:/home/aiRobots
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment: 
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"
    
  cpp:
    build: ./cpp
    image: axyz1288/cpp:kinetic
    runtime: nvidia
    user: aiRobots
    depends_on:
      - ros
    container_name: cpp
    privileged: true
    volumes:
      - ~/aiRobots/cpp:/home/aiRobots
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
    environment:
      - "ROS_HOSTNAME=cpp"
      - "ROS_MASTER_URI=http://ros:11311"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"

  base:
    build: ./python
    image: axyz1288/python:2.7-cuda10.1
    container_name: base
    
  pytorch:
    build: 
      context: ./pytorch
      shm_size: '128gb'
    image: axyz1288/pytorch:python2.7-cuda10.1
    user: aiRobots
    runtime: nvidia
    depends_on:
      - base
    container_name: pytorch
    ports:
      - "1000:8888"
      - "1001:6006"
    volumes:
      - ~/aiRobots/pytorch:/home/aiRobots
    environment:
      - "ROS_HOSTNAME=pytorch"
      - "ROS_MASTER_URI=http://ros:11311"

  horovod:
    build: 
      context: ./horovod
      shm_size: '128gb'
    network_mode: "host"
    image: axyz1288/horovod:python2.7-cuda10.1
    runtime: nvidia
    depends_on:
      - pytorch
    container_name: horovod
    volumes: 
      - ~/aiRobots/horovod:/home/aiRobots
  
  tensorflow:
    build: 
      context: ./tensorflow
      shm_size: '128gb'
    image: axyz1288/tensorflow:python2.7-cuda10.1
    user: aiRobots
    runtime: nvidia
    depends_on:
      - base
    container_name: tensorflow
    ports:
      - "1010:8888"
      - "1011:6006"
    volumes:
      - ~/aiRobots/tensorflow:/home/aiRobots
    environment:
      - "ROS_HOSTNAME=tensorflow"
      - "ROS_MASTER_URI=http://ros:11311"